# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G
org.gradle.daemon=false
org.gradle.parallel=true

## Environment Properties
# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
# The Minecraft version range
minecraft_version_range=[1.20.1,1.21)
# The Forge version
forge_version=47.4.0
# The Forge version range
forge_version_range=[47,)
# The loader version range
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=nebl
# The human-readable display name for the mod.
mod_name=NotEnoughBandwidthLegacy
# The license of the mod.
mod_license=GNU GPL 3.0
# The mod version. See https://semver.org/
mod_version=20.1.07-forge+1.20.1+47.4.0
# The group ID for the mod.
mod_group_id=cn.ussshenzhou
# The authors of the mod.
mod_authors=USS_Shenzhou
# The description of the mod.
mod_description=Not Enough Bandwidth - bandwidth optimization mod for Minecraft
